version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image:
- Visual Studio 2015
- Visual Studio 2017
build_script:
- cmd: >-
    pushd C:\projects\tensorflow-cmake
    
    cmake\scripts\configure.bat
    
    cmake\scripts\make.bat tf_python_build_pip_package
    
    popd
